### ISSUE TITLE
Reproducing RoBERTa*_ORA_P_D(last step) results

### ISSUE THREAD

**Issue by carlos-gemmell** [eladsegal/strategyqa#3]
Hi,

I am attempting to reproduce the numbers for the dev set for RoBERTa*_ORA_P_D(last step).
I am using downloaded checkpoints to minimise variability:
- generated decompositions with `transformer_qa_large.tar.gz` -> `transformer_qa_ORA-P_dev_no_placeholders.json` & `transformer_qa_ORA-P_train_no_placeholders.json`
- 8_STAR_ORA-P-D-last-step.tar.gz

My output when running this command 
```
$ python3 run_scripts/evaluate.py --model pre-trained_models/8_STAR_ORA-P-D-last-step/8_STAR_ORA-P-D-last-step.tar.gz --data data/strategyqa/dev.json -g "1"
[Lots of output, not included]
Traceback (most recent call last):
  File "/nfs/strategyqa/run_scripts/run.py", line 45, in run
    allennlp_main()
  File "/usr/local/lib/python3.6/dist-packages/allennlp/commands/__init__.py", line 118, in main
    args.func(args)
  File "/usr/local/lib/python3.6/dist-packages/allennlp/commands/evaluate.py", line 137, in evaluate_from_args
    instances = dataset_reader.read(evaluation_data_path)
  File "/usr/local/lib/python3.6/dist-packages/allennlp/data/dataset_readers/dataset_reader.py", line 234, in read
    instances = list(instances)
  File "/usr/local/lib/python3.6/dist-packages/tqdm/std.py", line 1130, in __iter__
    for obj in iterable:
  File "/nfs/strategyqa/src/data/dataset_readers/base/base_dataset_reader.py", line 77, in _read
    for instance in self._direct_read(file_path):
  File "/nfs/strategyqa/src/data/dataset_readers/strategy_qa_reader.py", line 102, in _direct_read
    instance = self._item_to_instance(self.json_to_item(json_obj))
  File "/nfs/strategyqa/src/data/dataset_readers/strategy_qa_reader.py", line 192, in _item_to_instance
    question, answer, decomposition, generated_decomposition, facts
  File "/nfs/strategyqa/src/data/dataset_readers/strategy_qa_reader.py", line 216, in text_to_instance
    facts=facts,
  File "/nfs/strategyqa/src/data/dataset_readers/strategy_qa_reader.py", line 283, in f
    if "unified" not in paragraphs:
TypeError: argument of type 'NoneType' is not iterable
```

Seeing that in `strategy_qa_reader.py` , `def _ora_p()` can return None and is then used by `generate_context_from_paragraphs()` 

```
def _ora_p(self, decomposition, **kwargs):
        if decomposition is None or len(decomposition) == 0:
            return None

        num_of_matchings = len(decomposition[0]["evidence_per_annotator"])
        if num_of_matchings == 0:
            return None

        all_evidence_ids = [
            [step["evidence_per_annotator"][i] for step in decomposition]
            for i in range(num_of_matchings)
        ]
      ...
      ...
      ...

def generate_context_from_paragraphs(self):
        def f(**kwargs):
            print("get_paragrarph kwargs = ", kwargs)
            paragraphs = self.get_paragraphs(**kwargs) <---- when this returns None

            if "unified" not in paragraphs: <----- This causes error
                paragraphs.update({"unified": None})
                return None, paragraphs
```

I modified `generate_context_from_paragraphs` like so to it can update the dictionary and not cash when iterating over None
```
def generate_context_from_paragraphs(self):
        def f(**kwargs):
            print("get_paragrarph kwargs = ", kwargs)
            paragraphs = self.get_paragraphs(**kwargs)
            if paragraphs == None:             <-------- new
                paragraphs = {}                      <-------- new
            if "unified" not in paragraphs:
```

The script then runs! But the accuracy seems quite lower than the paper.
```
$ python3 run_scripts/evaluate.py --model pre-trained_models/8_STAR_ORA-P-D-last-step/8_STAR_ORA-P-D-last-step.tar.gz --data data/strategyqa/dev.json -g "1"
[lots of output, skipping]
INFO:allennlp.training.util:Iterating over dataset
0it [00:00, ?it/s]INFO:allennlp.data.samplers.bucket_batch_sampler:No sorting keys given; trying to guess a good one
INFO:allennlp.data.samplers.bucket_batch_sampler:Using ['tokens'] as the sorting keys
accuracy: 0.57, loss: 1.70 ||: : 115it [00:03, 36.13it/s]
INFO:allennlp.common.util:Metrics: {
  "accuracy": 0.5720524017467249,
  "loss": 1.7002240842188021
}
INFO:allennlp.commands.evaluate:Finished evaluating.
```

I suspect doing a workaround like I did isn't the correct fix. (• ◡•)
Could you point me in the right direction to get similar results to those reported?

**Comment by eladsegal** [comment]
Hi, 
- The code was missing a small piece, fixed it now. But your fix was correct as well :)
- You should run `8_STAR_ORA-P-D-last-step.tar.gz` with `data/strategy_qa/transformer_qa_ORA-P_dev_no_placeholders.json` and not with `data/strategy_qa/dev.json`, because the model depends on using the last decomposition step without placeholders. I've updated the README file to mention it.

Thank you!

**Comment by carlos-gemmell** [comment]
Fabulous

**Comment by carlos-gemmell** [comment]
Using the following command I get 66.3% accuracy on DEV. Is that consistent with you @eladsegal ?
Seems a bit lower than the the test scores.

```
$ python3 run_scripts/evaluate.py --model pre-trained_models/8_STAR_ORA-P-D-last-step/8_STAR_ORA-P-D-last-step.tar.gz --data data/strategyqa/generated/transformer_qa_ORA-P_dev_no_placeholders.json -g "1"

INFO:allennlp.training.util:Iterating over dataset
0it [00:00, ?it/s]INFO:allennlp.data.samplers.bucket_batch_sampler:No sorting keys given; trying to guess a good one
INFO:allennlp.data.samplers.bucket_batch_sampler:Using ['tokens'] as the sorting keys
accuracy: 0.66, loss: 1.55 ||: : 115it [00:03, 35.74it/s]
INFO:allennlp.common.util:Metrics: {
  "accuracy": 0.6637554585152838,
  "loss": 1.5511564987638216
}
INFO:allennlp.commands.evaluate:Finished evaluating.
```

**Comment by carlos-gemmell** [comment]
Also @eladsegal. (• ◡•) 
Do you have dev scores for your linked models? 
particularly for RoBERTa*_IR_D if elasticsearch isn't an option for one right now.

**Comment by eladsegal** [comment]
Sure, I've added metrics for all of our trained models in the README.
And you got a correct result, indeed there's a difference between the dev and test results.

**Comment by carlos-gemmell** [comment]
Thank you for adding these!
Fascinating how RoBERTa* (non fine-tuned) gets 85.7% accuracy!

Any intuition why?
Noise in the dev set?

**Comment by eladsegal** [comment]
RoBERTa* is not evaluated on StrategyQA, but on BoolQ :)
It was mentioned in the notes below the models, but I've updated the README again so it will be more visible
