### ISSUE TITLE
An issue with strategy_qa_reader

### ISSUE THREAD

**Issue by yu-rovikov** [eladsegal/strategyqa#4]
Hi, i tried to reproduce the training procedure for the ORA-P setting (training with gold paragraphs and no decomposition), and I encountered a problem running this line (with pretrained RoBERTa* in `experiment_dumps/model.tar.gz`):

`python run_scripts/train.py --config-file configs/strategy_qa/6_STAR_ORA-P.jsonnet -g '[0,1]' -w 'experiment_dumps/model.tar.gz' -s 'ora-p_reproduce`

and I am getting the following error:

```
Traceback (most recent call last):
  File "run_scripts/train.py", line 100, in <module>
    main()
  File "run_scripts/train.py", line 96, in main
    return run(args)
  File "run_scripts/train.py", line 69, in run
    run_main()
  File "/home/jovyan/qa/strategy_qa/reproduce/run_scripts/run.py", line 53, in main
    run(args)
  File "/home/jovyan/qa/strategy_qa/reproduce/run_scripts/run.py", line 45, in run
    allennlp_main()
  File "/home/user/conda/lib/python3.7/site-packages/allennlp/commands/__init__.py", line 118, in main
    args.func(args)
  File "/home/user/conda/lib/python3.7/site-packages/allennlp/commands/train.py", line 119, in train_model_from_args
    file_friendly_logging=args.file_friendly_logging,
  File "/home/user/conda/lib/python3.7/site-packages/allennlp/commands/train.py", line 178, in train_model_from_file
    file_friendly_logging=file_friendly_logging,
  File "/home/user/conda/lib/python3.7/site-packages/allennlp/commands/train.py", line 292, in train_model
    params.duplicate(), serialization_dir, print_statistics=dry_run
  File "/home/user/conda/lib/python3.7/site-packages/allennlp/training/util.py", line 473, in make_vocab_from_params
    datasets = datasets_from_params(params, serialization_dir=serialization_dir)
  File "/home/user/conda/lib/python3.7/site-packages/allennlp/training/util.py", line 153, in datasets_from_params
    train_data = dataset_reader.read(train_data_path)
  File "/home/user/conda/lib/python3.7/site-packages/allennlp/data/dataset_readers/dataset_reader.py", line 234, in read
    instances = list(instances)
  File "/home/user/conda/lib/python3.7/site-packages/tqdm/std.py", line 1165, in __iter__
    for obj in iterable:
  File "/home/jovyan/qa/strategy_qa/reproduce/src/data/dataset_readers/base/base_dataset_reader.py", line 77, in _read
    for instance in self._direct_read(file_path):
  File "/home/jovyan/qa/strategy_qa/reproduce/src/data/dataset_readers/strategy_qa_reader.py", line 97, in _direct_read
    instance = self._item_to_instance(self.json_to_item(json_obj))
  File "/home/jovyan/qa/strategy_qa/reproduce/src/data/dataset_readers/strategy_qa_reader.py", line 187, in _item_to_instance
    question, answer, decomposition, generated_decomposition, facts
  File "/home/jovyan/qa/strategy_qa/reproduce/src/data/dataset_readers/strategy_qa_reader.py", line 211, in text_to_instance
    facts=facts,
  File "/home/jovyan/qa/strategy_qa/reproduce/src/data/dataset_readers/strategy_qa_reader.py", line 277, in f
    if "unified" not in paragraphs:
TypeError: argument of type 'NoneType' is not iterable
```

The problem is clearly in `strategy_qa_reader`: for some reason, it does not return any paragraphs, only `None`. 

All the datasets (including `strategyqa_train_paragraphs.jsonl`) are present in the directory. I am using `allennlp==1.2.1`

This issue is similar to the [issue](https://github.com/eladsegal/strategyqa/issues/3) by [aquaktus](https://github.com/aquaktus), but changing a piece of code in `strategy_qa_reader.py` (following your fix on March 19) did not help.

Thanks in advance!

**Comment by eladsegal** [comment]
Hi, there are a few examples for which the paragraphs failed to be retrieved. In training, we drop these examples.
The handling of such cases is done by returning `None` as `context` from `generate_context_from_paragraphs`, and I fixed it to behave correctly now.

**Comment by yu-rovikov** [comment]
Thanks a lot!
